# site properties and page defaults
title: Hi-PHI Lab
subtitle: The High-Performance Human Interfacing Laboratory
description: Developing transformative human interfacing technologies to enable a new era of human health.
header: https://uc3217e722d63d20aec9beaca01e.previews.dropboxusercontent.com/p/thumb/ACdghXPSMTMfq409U9eFVzwEKhvJ9wPuGcMrxPashS3cssudtGLeadawkAzBoAywxYtBb5Em9g9gGjy53AJwb8-cz7vwVuW9iKvH_OQ7Pico0UM7zdQBcpox65kKfpFn-asL_jJVTsp4u2EX6hcQlCSF1SvHiDCCBluIYvXr1O-zwkz2IXTbeAccY7ziafeGdVpHTJnL7Ku1BApomA7CfgL83u3wBF_I06Z6akj6RAbORwDLFEdnVYXe1yXxKIYGyHxkfkPvK2HM530nsy8L7ZkFALPfAPSHE1KAYqMjSyJea5V65-4SdQR27JgkQmzbEqmWs5hD_taWv5BTcugrV-_V66gSlHLUuXRQ80hKJO0msl6qTXwHMgkPd3p4NABVf-lBGEcppV776AKRVA-dfk4dDDpFMGIBhZpmyzCIoc-ApVMKe48OTwI3awpvjgha_ZbKEURlPvHBeOV26KW_a5j5xlDqGzc5gTUd_zo-TnjsZd9K-sZ4gN4v6-VDAhyWo2iNqjXRNi7mX5fQqdiNl3UlOHtP5K0adCi_tDwrvsip2PZTw_qyv7GL9iluNUgFJZc/p.png?is_prewarmed=true
footer: https://uc3217e722d63d20aec9beaca01e.previews.dropboxusercontent.com/p/thumb/ACdghXPSMTMfq409U9eFVzwEKhvJ9wPuGcMrxPashS3cssudtGLeadawkAzBoAywxYtBb5Em9g9gGjy53AJwb8-cz7vwVuW9iKvH_OQ7Pico0UM7zdQBcpox65kKfpFn-asL_jJVTsp4u2EX6hcQlCSF1SvHiDCCBluIYvXr1O-zwkz2IXTbeAccY7ziafeGdVpHTJnL7Ku1BApomA7CfgL83u3wBF_I06Z6akj6RAbORwDLFEdnVYXe1yXxKIYGyHxkfkPvK2HM530nsy8L7ZkFALPfAPSHE1KAYqMjSyJea5V65-4SdQR27JgkQmzbEqmWs5hD_taWv5BTcugrV-_V66gSlHLUuXRQ80hKJO0msl6qTXwHMgkPd3p4NABVf-lBGEcppV776AKRVA-dfk4dDDpFMGIBhZpmyzCIoc-ApVMKe48OTwI3awpvjgha_ZbKEURlPvHBeOV26KW_a5j5xlDqGzc5gTUd_zo-TnjsZd9K-sZ4gN4v6-VDAhyWo2iNqjXRNi7mX5fQqdiNl3UlOHtP5K0adCi_tDwrvsip2PZTw_qyv7GL9iluNUgFJZc/p.png?is_prewarmed=true
header-dark: false
footer-dark: false
proofer: false

# site social media and other links
links:
  email: ctaylor7@unc.edu
  orcid: 0000-0001-7618-0544
  google-scholar: ECmR0YkAAAAJ
  twitter: cameronrtaylor
  
### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
