# site properties and page defaults
title: Hi-PHI Lab
subtitle: The High-Performance Human Interfacing Laboratory
description: Developing transformative human interfacing technologies to enable a new era of human health.
header: https://uc6a13729dd34f9f9769d7310c7c.previews.dropboxusercontent.com/p/thumb/ACfC7Ydvl856Ts2mvNwXfm-F4XYnDfJgfHlKnXGNcsvJmgqFCZJi_NlzC-TEE3yvEtST-7HuE4QvfX0GNXDg_-cc3_5fNJvCGjidxjQswZZGM3ZVl0wYcNInGprrGH7pgHupRTkP4of0EJO94LkL-7my3FywZK139E0HkQnOnZHYcyT0jdk3lSOZ0TxBfnxjNiJks6AzdzUl9oH7ML6q97fu2te4zCIEq2gbepubbvKwAZ2gc9g-iCYLGfTi-nFPuXOkqVclBqVg39c8cM4gzqikN3z9cnsMo-001V-JvDF7rbtJ9KiwZ2IBRNWmgtHOx4tbr176HVv0bW7_7eDQ35Gy_iEM73MV5MwsO8vlrYrbktAwhfU9IUIy5nQ8_SYQpc6MDRDWg1ZoJdPDbnhs4ix-InaiiK1sHPNFsH12G5H4rGqLeHHf73jSsmV-N-hqHzAa0WX07RVacLQ6aNQ-BhglqygLBTSOjrm4XbeTyiPyLIIwDkpA5FP5MPUr8iAqCbCC_H8O7MfhFooI4jzdxzRdkWNMwWmu1E4jaQ-B01T8Ugnb-chDkU_tpLYpU5BDYcs/p.png?is_prewarmed=true
footer: https://uc6a13729dd34f9f9769d7310c7c.previews.dropboxusercontent.com/p/thumb/ACfC7Ydvl856Ts2mvNwXfm-F4XYnDfJgfHlKnXGNcsvJmgqFCZJi_NlzC-TEE3yvEtST-7HuE4QvfX0GNXDg_-cc3_5fNJvCGjidxjQswZZGM3ZVl0wYcNInGprrGH7pgHupRTkP4of0EJO94LkL-7my3FywZK139E0HkQnOnZHYcyT0jdk3lSOZ0TxBfnxjNiJks6AzdzUl9oH7ML6q97fu2te4zCIEq2gbepubbvKwAZ2gc9g-iCYLGfTi-nFPuXOkqVclBqVg39c8cM4gzqikN3z9cnsMo-001V-JvDF7rbtJ9KiwZ2IBRNWmgtHOx4tbr176HVv0bW7_7eDQ35Gy_iEM73MV5MwsO8vlrYrbktAwhfU9IUIy5nQ8_SYQpc6MDRDWg1ZoJdPDbnhs4ix-InaiiK1sHPNFsH12G5H4rGqLeHHf73jSsmV-N-hqHzAa0WX07RVacLQ6aNQ-BhglqygLBTSOjrm4XbeTyiPyLIIwDkpA5FP5MPUr8iAqCbCC_H8O7MfhFooI4jzdxzRdkWNMwWmu1E4jaQ-B01T8Ugnb-chDkU_tpLYpU5BDYcs/p.png?is_prewarmed=true
header-dark: false
footer-dark: false
proofer: false

# site social media and other links
links:
  email: ctaylor7@unc.edu
  orcid: 0000-0001-7618-0544
  google-scholar: ECmR0YkAAAAJ
  twitter: cameronrtaylor
  
### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
