- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1126/scirobotics.abg0656
  type: paper
  description: A pair of magnetic beads can be used for minimally-invasive muscle tissue length tracking.
  title: Magnetomicrometry
  authors:
  - C. R. Taylor
  - S. S. Srinivasan
  - S. H. Yeon
  - "M. K. O\u2019Donnell"
  - T. J. Roberts
  - H. M. Herr
  publisher: Science Robotics
  date: '2021-08-11'
  link: https://doi.org/gtvkpz
  orcid: 0000-0001-7618-0544
  plugin: orcid.py
  file: orcid.yaml
  buttons:
    - type: pdf
      link: pdfs/magnetomicrometry_authors_version.pdf