- id: doi:10.1126/scirobotics.abg0656
  title: Magnetomicrometry
  type: paper
  image: publications/icons/magnetomicrometry_icon.jpg
  description: A pair of magnetic beads can be used for minimally-invasive muscle tissue length tracking.
  authors:
  - C. R. Taylor
  - S. S. Srinivasan
  - S. H. Yeon
  - "M. K. O\u2019Donnell"
  - T. J. Roberts
  - H. M. Herr
  publisher: Science Robotics
  date: '2021-08-11'
  link: https://doi.org/gtvkpz
  plugin: orcid.py
  file: orcid.yaml
  buttons:
    - type: pdf
      link: publications/pdfs/magnetomicrometry_authors_version.pdf

- id: doi:10.36227/techrxiv.172954209.92752104/v1
  title: Metamorphic Flexure Bearings for Extended Range of Motion
  type: paper
  image: publications/icons/mfb_icon.png
  description: Metamorphic flexure bearings extend compliant mechanism benefits with a conventional bearing range of motion.
  authors:
  - Cameron Taylor
  - Will Flanagan
  - Talmage H. Jones
  - He Kai Lim
  - Jonathan B. Hopkins
  - Tyler R. Clites
  publisher: TechRxiv
  date: '2024-10-21'
  link: https://doi.org/g8qhwv